spring.application.name=agileDemo
spring.profiles.active=default
spring.data.mongodb.uri=mongodb://localhost:27017/techSupport
spring.data.mongodb.database=techSupport
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoOperations=DEBUG
#logging.level.org.mongodb.driver.protocol.command=DEBUG